hash-format = "sha256"

[[files]]
file = "mods/alexs-caves.pw.toml"
hash = "6f864eef65f9a38f57eb0cc6fc71469b36ea70444a10c3e27502d617c5eaf917"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "8d0321177fed4a0b48554c40158b43db62f6cdaa768f584ef6a11575dfaa6223"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "fe46309d954710019e07813bcdc6db2c775b07795f3628cb559610adcb129a9a"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "83ba38ab1e5b583227e9d37b8fea91ac1fcb4e2f67ba86800c5d7aa4024d2993"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "5a4b03567f23fe0aac7806bd7cc9734138bf5fc098e98c1bb552d5b288bef258"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "e3173aaa4e9078ad7ace2b9ef43ce15ce9919c0b566d8830cea87264f92b3a6a"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "5b0eaf19630d6145093ae6ff9a21cf2dbdd0da53d9289673ad5ccb099afa18b7"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "1e56f528d8e21b0cf9c52c3d6deea2a4eafa408170b39a070195dbf66617f373"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "28053b4a334c4079b5d4c7ea2d3b8d48f8fa61420498f1bed0ff83cd316bbba0"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "cfa8aa9c0437721dab2057c932c9cf8ec3d3a11f672040601305238d13df85e8"
metafile = true

[[files]]
file = "mods/ctm.pw.toml"
hash = "ff55f6dd98968c446e32885ec0eae66ee882071f8a4efbf1486e57590778b2eb"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "2eb26b157c4159bfeff6a00147afa35284397d558f84b55367d1a41064d7456a"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "1315cd56b0b4a5b3d53374cebf4f1f3cd0546b05058740847bd226c1d1ccab39"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "a1575677daaaf6ea6dac12e5a10073e34025e5ca2c35b6d36ad4a5a0edbc0e82"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "35ef939dd24fc39919a5a50c86e28468e1b3a178cdf61e8197dad72601f25ba5"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "5bd0506bc0be25116b234f2b5af9447f60d82ae1cb6c5be4e12d8841f6c2501c"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "88f142bda6bfa6aff4f4d4e12b8ba7581aa40e3f163039a533f09dd6d634e093"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "c46659c3e873e0ca121f5215991ae8bc989132a3fea0c2da9eed0f22a947b2b9"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "b9a7e71472f5f88229bf2f9e214b223b3900052bdc56075906d7a22acf74568c"
metafile = true

[[files]]
file = "mods/ice-and-fire-dragons.pw.toml"
hash = "94c7c45a70d0cea86695ecd467f8e5c22510442c53c44291a570986e234428e5"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "eb089373d47632a85bb7596b1143b719d7675f5e2782586aa0c340069d699700"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "8f359d190506a6f824763b8e7c390d9e22204ef11e3ffa5ef980000d17e2c2b6"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "29b62d42548542296d9932bcbb8a93ffba0b75b7cc859a67e596aeb1e048ace2"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "e8b4876d403b4f4daab64bad9704a5b271a33031d1ff8d19d23ebd1e3b8dd39a"
metafile = true

[[files]]
file = "mods/magichem.pw.toml"
hash = "22dbf559d806893a2a0cfa7bc5576e1fcf6bbbbe60c891b21c51ee65397246b0"
metafile = true

[[files]]
file = "mods/mana-and-artifice.pw.toml"
hash = "3435128be37d46d9c18039a8ec4aa9764da4fb39ff4197a4b1090fea0547641b"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "d1d3d37354453b07ebc001454a59edfabd6539ec59ed6cdcac93722f12fcf978"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "e72f73611904e14d915418f0e3c6cb483cdc600e211375c2eceb393fec5b80f1"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "820d6b97344411476b96ae2bc8a3e4b9e30e15dfd15d8d0c945726b0011928d4"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "1d602996f39fb6103a5b968f50ec06800db7125b145570474c9c10e6dcd0c68e"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml"
hash = "a4cf75dee4a240fb7788870b383e44e0bf00b3c93734bb9862775430fe03d886"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
hash = "4b4d83e721458f356072f309058dbdcc5ab490dd41b53764ec6305dcf30a6ed6"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8c65958007f81cdf1a57dac999ec7ffdde17cce6154c9a2f75bbb389fd11efbf"
metafile = true

[[files]]
file = "mods/rats.pw.toml"
hash = "c4b46cb349e3f111af5711429b444dcb790e73f312feb5f9b8e04cd41a9c7b75"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "ef0264b7d819848f72ab2f34643306187e712965a8246e1f733e1bd39d8fd681"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "2cb8dd9a3944a6430b49916a4fe1b6cf0bd7efd907054f8e679a02717149404f"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "4ed3bf205c8f6aa985b33a4cd082a519f7f9dc764d1dcee7e560668818690549"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "ee2d9154be68ef20293596a3f65810111fd35a802f1e8292e9ba8872de463a14"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "fde3d3b1607636100e382dce1bba80ab4608ebfa1ef888a37b86bc8c7dcbafe5"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "da60fdeff7103d9c04ece03d319a28b9c899dc8b30eb8f4c14d398944dc34aeb"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "9fb6a1a06b18f2ce7b0811200339d997925cb39bde220fbaea4d5c8067376c12"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "58148fa22c72e0b0eac5e35fed0be9194ad59fe848298c1b61b565fa3158b2f4"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "31fca121c5b55c624ed203937c8f9b4d13cfe32f80bb85405aa4c65238378b15"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "a5af976bf45b8e0aaaa22bebb11504ef0687e90d2cff9d3fa3b648c0757c1446"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-forge.pw.toml"
hash = "e0d77569aa19c6b72d30cb895cef575837a5740bee489d3ae537edf40a900ab1"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "f58f817a74f2b26fca9922263bf3f616deb0ee709212aa944ece857bf47a2d6e"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "32d07d192caa9459521c3b3bc21199ebe72d7f6cad9b3461e0b231180f46bb30"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "2eb3e909cc46e39d8b9e762f39c36b0579744118d619beb6a174d264951d6248"
metafile = true
