hash-format = "sha256"

[[files]]
file = "config/forge-client.toml"
hash = "1f776cff255a62036f2f721c1b516a20a49fd7fd11de442e36a19fe4ecd4f3a0"

[[files]]
file = "mods/accessories.pw.toml"
hash = "5d3f94d4280b3367a376f086018a4005866ddecbe80b6abb0849e5d995a98e9d"
metafile = true

[[files]]
file = "mods/alexs-caves.pw.toml"
hash = "fb27b11ac5530247eb26ef9a59ed0959596acd994d635c5ebcc385ae1682a792"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "5e1239fd67c97c042d09cf38664698c9d1a3cfbc50d779fc550c461cf6aeb565"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "2362e168d550f0a3a3bea1715a495d7c54fe6e9f159b948981eae15c53df597c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "2a6d398aa111a6448b1d4072e34f61294a517d2c8545cb0aa4239ea8ad63ce45"
metafile = true

[[files]]
file = "mods/aquaculture.pw.toml"
hash = "04aae524d364de0ec8ac66db6eaff094b9c9b9d69e5de89f11acb2a00ce35261"
metafile = true

[[files]]
file = "mods/aquamirae.pw.toml"
hash = "caf733526eccac9b26d70b2649d5fa99d832d16a2379a9aa2515049c77765077"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5e9edd1fd2395f14a0c8a4acbdbdd61e1047be1f0033deb3140d2ce0d093e9d8"
metafile = true

[[files]]
file = "mods/athena.pw.toml"
hash = "9638d8a308563842fd989970919a51f37ed1bcc82372bff47fc5a5c2e6de738e"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "8a700d602de5bde4557c97a10fb50a9ab7d215313a9b6dadf89283a0ff3c32aa"
metafile = true

[[files]]
file = "mods/better-archeology.pw.toml"
hash = "2adb8c4c9a368dac1980d99180bec4ff1ec51d8c01d73093bcc2610e95803cd9"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "6a144cc70e30220d743320fd99debd3aeab1dc6c4913cafa9cf8f02a020c5344"
metafile = true

[[files]]
file = "mods/blueprint.pw.toml"
hash = "790de162313fcbe950496580db107eb8da2ae29060cbf611764d1bb352461d03"
metafile = true

[[files]]
file = "mods/chalk.pw.toml"
hash = "f928175ba3f7fe5499a532622dd7dd85c2b6aeef84a2e50f7eb88c5d2cb8e563"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "71a33fe41bead909b3e95643351ef8015def70d3cb083916469f492f66434b45"
metafile = true

[[files]]
file = "mods/chunk-loaders.pw.toml"
hash = "913bbc46f7ebbae12ee05efee5810b4c56a027336acc929951ee3bae1f084275"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "1fd92086e15faed583c6dd42ebaa43ebeacaa4ca4fbe52d9210f8177b7a7c92c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "96204145e12506e0625d8b9bfa05aad54e9a62fd511bae39f0d57fcb5e39f4cc"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "c854f6b25bc61ad39b71ce03ae70aea0fb3f806c9cf4b24e50e8d0c81c832757"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "492359a6ce93fbf09eb6e1d20b761a5538fe9197e7d129949234d83b87e06bc1"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "58bf97ca61f74ea9a540f6e6090aef631155748c49b83a7a338b34d8dece9109"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "ddd7699a3abd3471af5313377a453fd5d9cef5317a0adcccb460a37087ba423c"
metafile = true

[[files]]
file = "mods/construction-wand.pw.toml"
hash = "1613f68b9bdd242a957a3a20c5193b640672d11087abcb5c3abe5da45b235e35"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "f56c370b32425962d0fe4a46b16a2e62fc50dc91ab415cd6ff1ae9630bddee70"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "7b1dd921e76b1e2b7b0b0262d423c8fa5202b8ee709c38ffab438ddd4252949c"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "e1483034960d3ddd4d4485c0e5f10430b71e766e94c13c47130ee40950f4e985"
metafile = true

[[files]]
file = "mods/ctm.pw.toml"
hash = "11ed2c2e93ec2bb1374b6124caf8dad5f088c1aa91bc6af1bc4f9a56593d2fa8"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "bb4b4e11518a8c5c2c6d6eaaf4ebbfa7c00ceb0c64d0019552602a12a11af399"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "b7325f1ad328f8cdc1cbd578570ce5244874fdd529eda5f20568df44dec5a772"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "b207d018bd9a51630c58b82d5f2e4b75847254b7dedfdcf0dbaf25278f3f107a"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "a1575677daaaf6ea6dac12e5a10073e34025e5ca2c35b6d36ad4a5a0edbc0e82"
metafile = true

[[files]]
file = "mods/endergetic.pw.toml"
hash = "d6d6f896494ce5a9c02fb11f8c929124d19308652f602bf530164cf5d204e6de"
metafile = true

[[files]]
file = "mods/extreme-sound-muffler.pw.toml"
hash = "978586ac2d00b1117b6af9a977dd8fa7d1e29b683aa0d13fc0f6455d7cade48c"
metafile = true

[[files]]
file = "mods/fantasy-armor.pw.toml"
hash = "db7410e867121bdfd2ae862e653111dae6fe3b33b1388fc205a906ae6cbe3f6d"
metafile = true

[[files]]
file = "mods/fastfurnace.pw.toml"
hash = "932ddad36de5cc064fd285cff392872050de95e262029d336e99f44e0ce01d97"
metafile = true

[[files]]
file = "mods/fastworkbench.pw.toml"
hash = "77095e78d0432b58d1243f271e953c8c6b318bf8dbd0563358b07e15baf30a9c"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "1bdf260b93529024685ade5d272bfeca5703b4a9fdb50bb86917e94834c60d8a"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "9e2175476f720e0b2d21b28e91873cecf5555648e2137310e1b7cf98f6b98ab8"
metafile = true

[[files]]
file = "mods/ftb-backups-2.pw.toml"
hash = "b3693e7a5647d4e28fc30ad3e85193c668a98a410dc3f425f19561cfea68957f"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "a1dba016bfd85fbabc5ff7c78f0302d3dd5b20026842231d6422947a7bb5f6f0"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "361a2451dc12db42636eed5aab8c03f8a281347504e0131346a3ec8b8273333b"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "b55f3276124e13e8b3899d4d0400e990dea41d228644be34b341e62fe8abed6e"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "5cc6ba3c65186988790abfb0213393f6b886fad92f33a097815b21672cfc2d32"
metafile = true

[[files]]
file = "mods/hourglass.pw.toml"
hash = "fbb371c2bb573d6d84600f10937f535b7f19f7df6e536f25b7b4e46471c32904"
metafile = true

[[files]]
file = "mods/ice-and-fire-dragons.pw.toml"
hash = "757e02e33252ae35ee2307996eef59f8b42d218db6ebb30164a230201312b7e6"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2621dfb5b3ad17a3adf927cc92a3bc6b0dd982c32f0265f920b29a61b34d182e"
metafile = true

[[files]]
file = "mods/immersive-armors.pw.toml"
hash = "a7fd74d5d5680775d2d9b83d8a4924c0244169ffb0961dadfb901a362eb1a935"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "2af801d2d7346615b495e173589d8835486f1aa6202b7fb997f78ca3092bceb0"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "8da51e31d146df07a51fa173d5c1d3f99affb78e478945e2c19f6af412212cd6"
metafile = true

[[files]]
file = "mods/inventory-tweaks-refoxed.pw.toml"
hash = "d182a82c1f048fc78ca7621c7555da5737d028d46f50e413059ca1c2b8a2e8c2"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "91fb39ac230e5f6b85fb45cd49c99c3806606c9f96e1961787c047675c4712b1"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "9482df68dbfa37997b45261992051d5dbcbb0d3d9f4ca766d548bcffdf825060"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "f3415c3e457db0c463de8257ba64729ba1f29a9fda1cc29fb882c97225145784"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "664a573384edf644e9b788c7c29fe32593917ac8283bb794cc46b471a0a6504a"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "de05b89fa3dcbba78114f1616a1852310873858de33671ba0ec5127c5dd88135"
metafile = true

[[files]]
file = "mods/lexiconfig.pw.toml"
hash = "e72b77792a8d646cb9ff26043d590041d3d8ed9aaedd0b097d5879c90525d70f"
metafile = true

[[files]]
file = "mods/log-begone.pw.toml"
hash = "dce6fa268df602cfa84ed377a253c80a1492994d5eeadde732fb74f72ecc742f"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "1cb3724c7ebb7f2aa92f0e5a0e422af6dfe74466135de0ca6bc282c8628bbd67"
metafile = true

[[files]]
file = "mods/magichem.pw.toml"
hash = "84ab79f472159b0ae4c5711769340771f131a798db0ee311402b520bd2858f79"
metafile = true

[[files]]
file = "mods/mana-and-artifice.pw.toml"
hash = "34368d9fda0f24c36faf7c9c32b48316541844eb4ef75373fc32ebb75f890609"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
hash = "6164ce697ea02e49911afd5666dcb1d5f83ed0fff9b290def0a7a7c440c1c39b"
metafile = true

[[files]]
file = "mods/mighty-mail.pw.toml"
hash = "b320c2f668b8789fd4d009899c7826862934129bb49f8cfc76a8164096020dce"
metafile = true

[[files]]
file = "mods/mnaoverpowered.pw.toml"
hash = "aac7f7cde7a28ced9a50cd791cf6e456e59642fe5952b61fdc05f4b389116efd"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "17523abe76f282db11e95a033e504c1da3f82ac23a42e169d6b1e4d59b6a18d6"
metafile = true

[[files]]
file = "mods/more-magichem-labels.pw.toml"
hash = "950207c1fa99e56225e2215b1efdd1ed57241d3ca76ed3553414b602733c652d"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "a9b313e2144b4b437d05e94ac6c7c583d8c6f0585efb1cd7c40d02540af045c5"
metafile = true

[[files]]
file = "mods/moyai.pw.toml"
hash = "8b2ccdad103cc06f03613e0df6654459159707596467b685d98920cbdc27db08"
metafile = true

[[files]]
file = "mods/mystical-oak-tree.pw.toml"
hash = "e37f81b9e82e757ba91a3efc644ec63dfcac7f89d87a83032f02ea637b955f52"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "832184ddd91539e06f1e176eed000a59c4a9ee81aa0447c4caedf98dc6c0f192"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7360013364f71b7967296d87a994a8e510e893ec9cfabd6e243293a6998189ca"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "215cb5123319ccd019db178b94ab2ab70db66a11c1b0ae722afefea885396e7a"
metafile = true

[[files]]
file = "mods/obscure-api.pw.toml"
hash = "96008b869b133a400c97313afa460bda3b4d43aeddcafaf04c4141f9193f3095"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml"
hash = "3efaf9fdcb2c72a5f5a98431bd0f9002a6e30ae458b6d6d712d86f9dfc4c016e"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
hash = "30327131c2d8ecc468417b5b61f974a3cc5ee3ef66245d8931e604c8ca5af289"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "045d582e2c534c5bb96d7336b4ae2cd12692c6de29b19ae5f1dbfd8759c03b03"
metafile = true

[[files]]
file = "mods/polylib.pw.toml"
hash = "947d5f3b9213360b68e9b65a8d2d5111939e82e248cf61eb02137f119c6eaeb6"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "6b5af5436645a6d990324f845314edbcdc9977131f7ea2b79694ef97f011cc51"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "5ca42f4c23aee558ed76923d4fb92ecee736ebacb53790445c09d46bd9ccb27e"
metafile = true

[[files]]
file = "mods/rats.pw.toml"
hash = "e7b0b4347c718c5b6ba50334d950a7f004348bfeb0dfd2b747c1f35d3145c966"
metafile = true

[[files]]
file = "mods/reds-more-structures.pw.toml"
hash = "27ab5fcaaa1822897794ad7f44e1e5ea1b297e0e4a6dc73038347f53ef268f5b"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "8d9cfd22181ae67b178a4ce2e29c05262170fbfba46435dbfb090e73856e0c88"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "33232510f247888ae35f261b26345f0f3c5f0daee0adbc0311aac2d5bb324a1d"
metafile = true

[[files]]
file = "mods/sawmill.pw.toml"
hash = "03df4d26153286220dd3e423d9682b90764ee827685e8e2969c74a9ee11a40e0"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "e461c1d7534ab618fc1ff30071f4342b1de2bd8037b8ee0238530c7552c32b07"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "f9834af674abc824248bedb2e490ab426cff92b036cb20413cbbacd67ec6f5e3"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "a811fe1e9fc7a2eeb10909881a714644bccfed5b4887d61f84a20b073b1fcd4c"
metafile = true

[[files]]
file = "mods/simple-voice-radio.pw.toml"
hash = "7bb9b367774fd68ce3e0c600f41f5c882b2232a203d3132b7224229ae73f9534"
metafile = true

[[files]]
file = "mods/simplehats.pw.toml"
hash = "33939c251677f80d437385995c129840636a24492a0b5996c16159bb0f930338"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "2a01c44a42ea70044149fdb717a3aefd1962d50beac5b69bf4343b2b1f56a176"
metafile = true

[[files]]
file = "mods/spartan-shields.pw.toml"
hash = "866baca6c0bd619c207a372afb52b4ea99dc06f435f02fdf3363ddb7eef8342e"
metafile = true

[[files]]
file = "mods/spartan-weaponry-addon-toolkit.pw.toml"
hash = "319c31c4fd88146a7239e6903de802b6a50cc9d5ab35074537aaa0d9680d0e12"
metafile = true

[[files]]
file = "mods/spartan-weaponry-ice-and-fire.pw.toml"
hash = "39a17d3a5056ced1c3c0d94857e7a5e5e2cf8de1ff0ce107051f1b6ef6099111"
metafile = true

[[files]]
file = "mods/spartan-weaponry.pw.toml"
hash = "74ea4dfd995e75e83d0e0ffc80ffa97c80f56563e1affaf65837c916f38407fa"
metafile = true

[[files]]
file = "mods/stoneworks.pw.toml"
hash = "7262f4ef1f6a42e2348537571f2adf9453381ead2a7cc2bff7384b8bbe45cc84"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "371b68e257eaca322ca4e95f4aa8d95441d84110b69243dda818f743a0111ba5"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "3eede8a7ebafb69840153ff51dbc879b0232799e90a834ab6d71274b1316179f"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "40a73f377f8dcf95c0e801bdc69e68bc4a2d29ec0bcf17f4dcb1a78f887021d1"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "261f9601fad172fab2fe4f5d6c7b265f9635993f2f8ba4d3d009ab3fca06647c"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
hash = "74a64acbd2275c16e47fb17e74bcd431779674cefa1f54f67f15b4d9b955aec7"
metafile = true

[[files]]
file = "mods/toast-control.pw.toml"
hash = "1195cdfa90ac4ef4d5ebed8dbca1df990cf58b0a0fe3b9b965ccefa0cfd5a2e3"
metafile = true

[[files]]
file = "mods/travelers-backpack.pw.toml"
hash = "1f1a8122f7fa9acb98adfab70d8f073850f2979b493e5bba6dbaeb03d7957613"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
hash = "75ac47ef3a388aa5416f86415f79d262f68f5c8195c7a1a89f081b348a64c81f"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "00bea828d2a2636dd46541b5f98cd067a9ba1c1a659849586c5096873b86a19c"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "0cb70caa22009a495a64a4332480b5ae80cb7fc7ba34c0a48ab8aff7df20b4f7"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "0100f1896b5898927e26d915f279d9323d8733add4df93fe2c4f15bbf63c139f"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "17303e372214dd58bce07d0a8e24f3ef7a051b338e93a92243b219f4952b57ec"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "78e8eda0880bcfb641ccb288c8a400f88cbe2a2c9a385e96818ac8b0c743f440"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "9b162867e984afd4e79897f66edda64fc4bfbf854c27287f8cd86c483a810259"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-forge.pw.toml"
hash = "1fed82be78179b17a6e1f1448c817c30cb2c4886a8f0b42d8075310e4c1d58ca"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "791084bdf5b5277afa32e1b4e628feab06178fe649d7cbf3178c4b387a667c80"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "d68b773e72ba1e60e190176222e8d103146d5a8a9668d7c1b6a4108f242550b1"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "48f6072913910cc732d977696873ae076f073fff1b0625583cd28ca3c15aaaff"
metafile = true
