hash-format = "sha256"

[[files]]
file = "mods/alexs-caves.pw.toml"
hash = "fb27b11ac5530247eb26ef9a59ed0959596acd994d635c5ebcc385ae1682a792"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "2362e168d550f0a3a3bea1715a495d7c54fe6e9f159b948981eae15c53df597c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "2a6d398aa111a6448b1d4072e34f61294a517d2c8545cb0aa4239ea8ad63ce45"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5e9edd1fd2395f14a0c8a4acbdbdd61e1047be1f0033deb3140d2ce0d093e9d8"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "8a700d602de5bde4557c97a10fb50a9ab7d215313a9b6dadf89283a0ff3c32aa"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "6a144cc70e30220d743320fd99debd3aeab1dc6c4913cafa9cf8f02a020c5344"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "1fd92086e15faed583c6dd42ebaa43ebeacaa4ca4fbe52d9210f8177b7a7c92c"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "c854f6b25bc61ad39b71ce03ae70aea0fb3f806c9cf4b24e50e8d0c81c832757"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "ddd7699a3abd3471af5313377a453fd5d9cef5317a0adcccb460a37087ba423c"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "f56c370b32425962d0fe4a46b16a2e62fc50dc91ab415cd6ff1ae9630bddee70"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "7b1dd921e76b1e2b7b0b0262d423c8fa5202b8ee709c38ffab438ddd4252949c"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "e1483034960d3ddd4d4485c0e5f10430b71e766e94c13c47130ee40950f4e985"
metafile = true

[[files]]
file = "mods/ctm.pw.toml"
hash = "11ed2c2e93ec2bb1374b6124caf8dad5f088c1aa91bc6af1bc4f9a56593d2fa8"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "bb4b4e11518a8c5c2c6d6eaaf4ebbfa7c00ceb0c64d0019552602a12a11af399"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "b7325f1ad328f8cdc1cbd578570ce5244874fdd529eda5f20568df44dec5a772"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "a1575677daaaf6ea6dac12e5a10073e34025e5ca2c35b6d36ad4a5a0edbc0e82"
metafile = true

[[files]]
file = "mods/extreme-sound-muffler.pw.toml"
hash = "978586ac2d00b1117b6af9a977dd8fa7d1e29b683aa0d13fc0f6455d7cade48c"
metafile = true

[[files]]
file = "mods/fastfurnace.pw.toml"
hash = "932ddad36de5cc064fd285cff392872050de95e262029d336e99f44e0ce01d97"
metafile = true

[[files]]
file = "mods/fastworkbench.pw.toml"
hash = "77095e78d0432b58d1243f271e953c8c6b318bf8dbd0563358b07e15baf30a9c"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "1bdf260b93529024685ade5d272bfeca5703b4a9fdb50bb86917e94834c60d8a"
metafile = true

[[files]]
file = "mods/ftb-backups-2.pw.toml"
hash = "b3693e7a5647d4e28fc30ad3e85193c668a98a410dc3f425f19561cfea68957f"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "ace5508365a9ab2bd2d3623233ebcc73c1f5b6056d44d9a4b696b67c43283a77"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "361a2451dc12db42636eed5aab8c03f8a281347504e0131346a3ec8b8273333b"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "b55f3276124e13e8b3899d4d0400e990dea41d228644be34b341e62fe8abed6e"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "5cc6ba3c65186988790abfb0213393f6b886fad92f33a097815b21672cfc2d32"
metafile = true

[[files]]
file = "mods/ice-and-fire-dragons.pw.toml"
hash = "757e02e33252ae35ee2307996eef59f8b42d218db6ebb30164a230201312b7e6"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "3435f5b8a9cb39cb372ce8053b60a12c6930350644212065e11e37e637118de7"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "c006beeec7fca82263506ab1fda78e472e54bb64be350e130902f4f475df25cb"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "91fb39ac230e5f6b85fb45cd49c99c3806606c9f96e1961787c047675c4712b1"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "f3415c3e457db0c463de8257ba64729ba1f29a9fda1cc29fb882c97225145784"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "de05b89fa3dcbba78114f1616a1852310873858de33671ba0ec5127c5dd88135"
metafile = true

[[files]]
file = "mods/lexiconfig.pw.toml"
hash = "e72b77792a8d646cb9ff26043d590041d3d8ed9aaedd0b097d5879c90525d70f"
metafile = true

[[files]]
file = "mods/log-begone.pw.toml"
hash = "dce6fa268df602cfa84ed377a253c80a1492994d5eeadde732fb74f72ecc742f"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "1cb3724c7ebb7f2aa92f0e5a0e422af6dfe74466135de0ca6bc282c8628bbd67"
metafile = true

[[files]]
file = "mods/magichem.pw.toml"
hash = "84ab79f472159b0ae4c5711769340771f131a798db0ee311402b520bd2858f79"
metafile = true

[[files]]
file = "mods/mana-and-artifice.pw.toml"
hash = "34368d9fda0f24c36faf7c9c32b48316541844eb4ef75373fc32ebb75f890609"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "183d06bd5159b829bf2efd9437c94e5ea2aa2541d6023e1aec08e84717d62b1f"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "a9b313e2144b4b437d05e94ac6c7c583d8c6f0585efb1cd7c40d02540af045c5"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "832184ddd91539e06f1e176eed000a59c4a9ee81aa0447c4caedf98dc6c0f192"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7360013364f71b7967296d87a994a8e510e893ec9cfabd6e243293a6998189ca"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml"
hash = "3efaf9fdcb2c72a5f5a98431bd0f9002a6e30ae458b6d6d712d86f9dfc4c016e"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
hash = "30327131c2d8ecc468417b5b61f974a3cc5ee3ef66245d8931e604c8ca5af289"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "045d582e2c534c5bb96d7336b4ae2cd12692c6de29b19ae5f1dbfd8759c03b03"
metafile = true

[[files]]
file = "mods/polylib.pw.toml"
hash = "947d5f3b9213360b68e9b65a8d2d5111939e82e248cf61eb02137f119c6eaeb6"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "6b5af5436645a6d990324f845314edbcdc9977131f7ea2b79694ef97f011cc51"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "5ca42f4c23aee558ed76923d4fb92ecee736ebacb53790445c09d46bd9ccb27e"
metafile = true

[[files]]
file = "mods/rats.pw.toml"
hash = "e7b0b4347c718c5b6ba50334d950a7f004348bfeb0dfd2b747c1f35d3145c966"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "8d9cfd22181ae67b178a4ce2e29c05262170fbfba46435dbfb090e73856e0c88"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "e461c1d7534ab618fc1ff30071f4342b1de2bd8037b8ee0238530c7552c32b07"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "a811fe1e9fc7a2eeb10909881a714644bccfed5b4887d61f84a20b073b1fcd4c"
metafile = true

[[files]]
file = "mods/simple-voice-radio.pw.toml"
hash = "7bb9b367774fd68ce3e0c600f41f5c882b2232a203d3132b7224229ae73f9534"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "2a01c44a42ea70044149fdb717a3aefd1962d50beac5b69bf4343b2b1f56a176"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "371b68e257eaca322ca4e95f4aa8d95441d84110b69243dda818f743a0111ba5"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "261f9601fad172fab2fe4f5d6c7b265f9635993f2f8ba4d3d009ab3fca06647c"
metafile = true

[[files]]
file = "mods/toast-control.pw.toml"
hash = "1195cdfa90ac4ef4d5ebed8dbca1df990cf58b0a0fe3b9b965ccefa0cfd5a2e3"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "00bea828d2a2636dd46541b5f98cd067a9ba1c1a659849586c5096873b86a19c"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "0cb70caa22009a495a64a4332480b5ae80cb7fc7ba34c0a48ab8aff7df20b4f7"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "0100f1896b5898927e26d915f279d9323d8733add4df93fe2c4f15bbf63c139f"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "17303e372214dd58bce07d0a8e24f3ef7a051b338e93a92243b219f4952b57ec"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "78e8eda0880bcfb641ccb288c8a400f88cbe2a2c9a385e96818ac8b0c743f440"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "9b162867e984afd4e79897f66edda64fc4bfbf854c27287f8cd86c483a810259"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-forge.pw.toml"
hash = "1fed82be78179b17a6e1f1448c817c30cb2c4886a8f0b42d8075310e4c1d58ca"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "791084bdf5b5277afa32e1b4e628feab06178fe649d7cbf3178c4b387a667c80"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "d68b773e72ba1e60e190176222e8d103146d5a8a9668d7c1b6a4108f242550b1"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "48f6072913910cc732d977696873ae076f073fff1b0625583cd28ca3c15aaaff"
metafile = true
