name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb7075e90d5b6eb6887fd14d4211b18834aab749771d547fd603decd340d5d8e"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
