name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2eafa3ae851394dbe26cc24428e48814fa409faa3c8b574c436a5aaac3dbae80"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
