name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b18cbd0e594308401e7865126d6795ec543a9ad514f13a6eab56521f79aa8c9"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
