name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bacc27607739add5ac997ff7ca72ea882c350fc2806e2deccbd8c37ce8b30051"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
