name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f23b65324be582d22f7b63cfd7c769c13e75da298f931825c58c126743fd392"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
