name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af7bb1d1ad1eeff993e9795ad958c08d9565a96cf8aa31573465d729895a4b00"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
