name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "817153c36ab78a061f3b2397dc6ddfb29783e4a07802a9213278a626f3a376f1"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
