name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5e3fa2591c11065c58ce88c85313e4799bca4426b1a402f013b8cd01d817112"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
