name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ffb27b2ee04959352a0562bc2c7267dac70d6329b6e5c6189ee9e17ec890085"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
