name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed59994cc0e474ee2bf0891a1242c151c9f33015eb4d7a2b46651652caa397e7"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
