name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab406b656dd5046adc7a7017cc19e4f7994524437c3a500ca63f713f9484e37b"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
