name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c144c6aa5367688b551765486d9e9c494770b946ce059f191c1ec1914f583c4"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
