name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41738f42e3925fd8c3b865bfef8ef2c831a783e1e6e311f34ebc79e0546a1be5"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
