name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46e529249e3890fcf75864d1ca1aa18885db6232466057303ea0f9b62e4b6483"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
