name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e032a93400c509c587dd0e90421a17f9bc17332592e67e2b9483c80330700477"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
